# Generated by Django 3.2.7 on 2021-09-23 17:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=app.models.generate_code, max_length=8, unique=True),
        ),
    ]
