# Generated by Django 3.2.7 on 2021-09-26 16:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_savefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='name',
            field=models.FileField(db_index=True, upload_to=app.models.user_directory_path),
        ),
    ]
