# Generated by Django 3.2.7 on 2021-09-27 06:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_savefile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savefile',
            name='name',
        ),
        migrations.AddField(
            model_name='savefile',
            name='file',
            field=models.FileField(blank=True, db_index=True, upload_to=app.models.user_directory_path),
        ),
    ]
