# Generated by Django 3.2.7 on 2021-09-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210928_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
