# Generated by Django 3.2.7 on 2021-09-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_savefile_json_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileForm',
        ),
    ]
