# Generated by Django 3.2.7 on 2021-09-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_uploadfileform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savefile',
            name='json_data',
        ),
        migrations.AddField(
            model_name='savefile',
            name='token',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
