# Generated by Django 3.2.7 on 2021-09-29 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210928_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='savefile',
            name='token',
        ),
        migrations.AddField(
            model_name='savefile',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.folderuser', verbose_name='Path'),
        ),
    ]
