# Generated by Django 3.2.7 on 2021-10-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210928_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.folderuser', verbose_name='Path'),
        ),
    ]
